---
# tasks file for osp-facts
   - name: Fetch Instance Info
     os_server_info:
      cloud: openstack
     register: result

   - name: Start servers
     os_server_action:
       cloud: openstack
       action: start
       server: "{{ item }}"
     loop: >-
       {{ result | json_query("openstack_servers[?status=='SHUTOFF'].name") }} 
     loop_control:
       label: "{{ item }}"

   - name: esperar que los servidores  responda en el puerto 22
     wait_for:
       host: "{{ item.public_v4 }}"
       port: 22
     loop: "{{ result.openstack_servers }}"
     loop_control:
       label: "{{ item.name }}"

   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      ansible_host: "{{ item.public_v4 }}"
      group: "{{ item.metadata.group }}"
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
     with_items: "{{result.openstack_servers}}"
   - name: Add host
     add_host:
      name: "{{ item.public_v4 }}"
      ansible_host: "{{ item.public_v4 }}"
      group: "{{ item.metadata.deployment_name }}"
      ansible_ssh_private_key_file: ~/.ssh/openstack.pem
      ansible_ssh_user: cloud-user
      ansible_ssh_extra_args: '-o StrictHostKeyChecking=no'
     with_items: "{{result.openstack_servers}}"


   - name: Wait for connection to hosts
     wait_for_connection:
       timeout: 600

   - name: Ping hosts
     ping: {}
     retries: 10
     delay: 5
     register: r_ping
     until: not r_ping.failed

